settings/urls.py
from django.urls import path
from .views import  home_view,category_filter_view,contact_view
urlpatterns = [
    path('',home_view,name='home_page'),
    path('category_filter/<int:navbar_id>/',category_filter_view, name='category_filter_page'),
    path('contact/',contact_view,name='contact_page'),
    
]

texnosite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('settings.urls'))
]

urlpatterns += static (
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)
urlpatterns += static (
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

settings/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField, IntegerField, NullBooleanField, URLField
# Create your models here.
class NavbarModel(models.Model):
    title = models.CharField(max_length=100, null=True, blank=True)
    category = models.BooleanField(default=False)
    url = models.URLField()
    def __str__(self):
        return f'{self.title}'

class CategoryModel(models.Model):
    url = URLField(null=True,blank=True)
    subcategory = models.BooleanField(default=False)
    category_id = models.ManyToManyField('NavbarModel')
    style = models.CharField(max_length=100, null=True, blank=True)
    def __str__(self):
        return f'{self.style}'
        
class Products(models.Model):
    category = models.ForeignKey(CategoryModel, on_delete=CASCADE, blank=True, null=True, related_name="products")
    image = models.ImageField(upload_to = "products/", null=True, blank=True)
    name = models.CharField(max_length=100,null=True,blank=True)
    price = models.FloatField(null=True,blank=True)
    delete_price = models.FloatField(null=True,blank=True)

class BackgroundImageModel(models.Model):
    sale = models.CharField(max_length=100,null=True,blank=True)
    image_text = models.CharField(max_length=100,null=True,blank=True)
    background_image = models.ImageField(upload_to='images_folder',null=True,blank=True)
    title = models.CharField(max_length=100,null=True,blank=True)

class ImageModel(models.Model):
    images = models.ImageField(upload_to="images_folder",null=True,blank=True)
    sale = models.CharField(max_length=100,null=True,blank=True)
    title = models.CharField(max_length=100,null=True,blank=True)
    
class ContactModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=1000)

class CreatorModel(models.Model):
    name = models.CharField(max_length=30, null=True, blank=True)
    profession = models.CharField(max_length=30, null=True, blank=True)
    company = models.CharField(max_length=300, null=True, blank=True)
    photo = models.ImageField(upload_to="images_folder", null=True, blank=True)
    about = models.CharField(max_length=100, null=True, blank=True)

class ClientBrandModel(models.Model):
    photo = models.ImageField(upload_to = "images_folder", null = True, blank = True)
    alt_name = models.CharField(max_length=15, blank=True, null=True)

class ContactUsModel(models.Model):
    name = models.CharField(max_length=30, null=True, blank=True)
    adress = models.CharField(max_length=45, null=True, blank=True)
    number = models.IntegerField( null=True, blank=True)
    email = models.EmailField(max_length=30, null=True, blank= True)
    wdigets = models.ImageField(upload_to = "images_folder", null=True, blank = True)
    widgets_url = models.URLField(max_length =100 ,null=True, blank=True)

settings/views.py
from django.http import request
from django.shortcuts import render, redirect



from settings.models import CategoryModel, BackgroundImageModel, ClientBrandModel, ContactUsModel, CreatorModel, ImageModel,NavbarModel, Products, ContactModel

# Create your views here.
def home_view(request):
    context ={}
    navbar_queryset = NavbarModel.objects.all()
    category_queryset = CategoryModel.objects.all()
    product_queryset = Products.objects.all()
    backgroundimage_queryset = BackgroundImageModel.objects.all()
    image_queryset = ImageModel.objects.all()
    creator_queryset = CreatorModel.objects.all()
    client_brand_queryset = ClientBrandModel.objects.all()
    contact_us_view = ContactUsModel.objects.all()
    # products = Products.objects.filter(product_id=category_id)
    # context['products'] = products
    context['category_queryset'] = category_queryset
    context['navbar_queryset'] = navbar_queryset
    context['product_queryset'] = product_queryset
    context['backgroundimage_queryset'] = backgroundimage_queryset
    context['image_queryset'] = image_queryset
    context['creator_queryset'] = creator_queryset
    context['client_brand_queryset'] = client_brand_queryset
    context['contact_us_view'] = contact_us_view
    if request.GET.get("category", None):
        context['product_queryset'] = context['product_queryset'].filter(category__style = request.GET.get("category"))
         
    return render(request,'index.html',context)


def category_filter_view(request,navbar_id):
    context = {}
    categories = CategoryModel.objects.filter(category_id=navbar_id)
    context['categories'] = categories
    return render(request,'category_filter.html', context)

# def product_view(request,category_id):
#     context={}
#     products = Products.objects.filter(product_id=category_id)
#     context['products'] = products
#     return render(request,'index.html',context)

def contact_view(request):
    context = {}
    if request.method == 'POST':
        name = request.POST.get('name',None)
        email = request.POST.get('email',None)
        subject = request.POST.get('subject',None)
        message = request.POST.get('message',None)
        ContactModel.objects.create(
            name = name,
            email = email,
            subject = subject,
            message = message
        )
        return redirect('home_page')
    else:
        return render(request,'contact.html',context) 
    return render(request,'contact.html',context)


def client_brand_view(request):
    context = {}
    client_brand_queryset = ClientBrandModel.objects.all()
    context['client_brand_queryset'] = client_brand_queryset
    return render(request, 'index.html', context)
 

settings/templates/base.html
{% load static%}
  <html lang="en">
    <head>
            <!-- / wpf loader Two -->       
  <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-chevron-up"></i></a>
    <!-- END SCROLL TOP BUTTON -->
  
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">    
      <title>Daily Shop | Home</title>
      
      <!-- Font awesome -->
      <link href="{% static 'asserts/css/font-awesome.css' %}" rel="stylesheet">
      <!-- Bootstrap -->
      <link href="{% static 'asserts/css/bootstrap.css' %}" rel="stylesheet">   
      <!-- SmartMenus jQuery Bootstrap Addon CSS -->
      <link href="{% static 'asserts/css/jquery.smartmenus.bootstrap.css' %}" rel="stylesheet">
      <!-- Product view slider -->
      <link rel="stylesheet" type="text/css" href="{% static 'asserts/css/jquery.simpleLens.css'%}">    
      <!-- slick slider -->
      <link rel="stylesheet" type="text/css" href="{% static 'asserts/css/slick.css'%}">
      <!-- price picker slider -->
      <link rel="stylesheet" type="text/css" href="{% static 'asserts/css/nouislider.css' %}">
      <!-- Theme color -->
      <link id="switcher" href="{% static 'asserts/css/theme-color/default-theme.css' %}" rel="stylesheet">
      <!-- <link id="switcher" href="css/theme-color/bridge-theme.css" rel="stylesheet"> -->
      <!-- Top Slider CSS -->
      <link href="{% static 'asserts/css/sequence-theme.modern-slide-in.css' %}" rel="stylesheet" media="all">
  
      <!-- Main style sheet -->
      <link href="{% static 'asserts/css/style.css' %}" rel="stylesheet">    
  
      <!-- Google Font -->
      <link href="{% static 'asserts/https://fonts.googleapis.com/css?family=Lato' %}" rel='stylesheet' type='text/css'>
      <link href="{% static 'asserts/https://fonts.googleapis.com/css?family=Raleway' %}" rel='stylesheet' type='text/css'>
      
  
      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    
  
    </head>
    <header id="aa-header">
        <!-- start header top  -->
        <div class="aa-header-top">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="aa-header-top-area">
                  <!-- start header top left -->
                  <div class="aa-header-top-left">
                    <!-- start language -->
                    <div class="aa-language">
                      <div class="dropdown">
                        <a class="btn dropdown-toggle" href="#" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                          <img src="img/flag/english.jpg" alt="english flag">ENGLISH
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                          <li><a href="#"><img src="img/flag/french.jpg" alt="">FRENCH</a></li>
                          <li><a href="#"><img src="img/flag/english.jpg" alt="">ENGLISH</a></li>
                        </ul>
                      </div>
                    </div>
                    <!-- / language -->
    
                    <!-- start currency -->
                    <div class="aa-currency">
                      <div class="dropdown">
                        <a class="btn dropdown-toggle" href="#" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                          <i class="fa fa-usd"></i>USD
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                          <li><a href="#"><i class="fa fa-euro"></i>EURO</a></li>
                          <li><a href="#"><i class="fa fa-jpy"></i>YEN</a></li>
                        </ul>
                      </div>
                    </div>
                    <!-- / currency -->
                    <!-- start cellphone -->
                    <div class="cellphone hidden-xs">
                      <p><span class="fa fa-phone"></span>00-62-658-658</p>
                    </div>
                    <!-- / cellphone -->
                  </div>
                  <!-- / header top left -->
                  <div class="aa-header-top-right">
                    <ul class="aa-head-top-nav-right">
                      <li><a href="account.html">My Account</a></li>
                      <li class="hidden-xs"><a href="wishlist.html">Wishlist</a></li>
                      <li class="hidden-xs"><a href="cart.html">My Cart</a></li>
                      <li class="hidden-xs"><a href="checkout.html">Checkout</a></li>
                      <li><a href="" data-toggle="modal" data-target="#login-modal">Login</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- / header top  -->
    
        <!-- start header bottom  -->
        <div class="aa-header-bottom">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="aa-header-bottom-area">
                  <!-- logo  -->
                  <div class="aa-logo">
                    <!-- Text based logo -->
                    <a href="index.html">
                      <span class="fa fa-shopping-cart"></span>
                      <p>daily<strong>Shop</strong> <span>Your Shopping Partner</span></p>
                    </a>
                    <!-- img based logo -->
                    <!-- <a href="index.html"><img src="img/logo.jpg" alt="logo img"></a> -->
                  </div>
                  <!-- / logo  -->
                   <!-- cart box -->
                  <div class="aa-cartbox">
                    <a class="aa-cart-link" href="#">
                      <span class="fa fa-shopping-basket"></span>
                      <span class="aa-cart-title">SHOPPING CART</span>
                      <span class="aa-cart-notify">2</span>
                    </a>
                    <div class="aa-cartbox-summary">
                      <ul>
                        <li>
                          <a class="aa-cartbox-img" href="#"><img src="img/woman-small-2.jpg" alt="img"></a>
                          <div class="aa-cartbox-info">
                            <h4><a href="#">Product Name</a></h4>
                            <p>1 x $250</p>
                          </div>
                          <a class="aa-remove-product" href="#"><span class="fa fa-times"></span></a>
                        </li>
                        <li>
                          <a class="aa-cartbox-img" href="#"><img src="img/woman-small-1.jpg" alt="img"></a>
                          <div class="aa-cartbox-info">
                            <h4><a href="#">Product Name</a></h4>
                            <p>1 x $250</p>
                          </div>
                          <a class="aa-remove-product" href="#"><span class="fa fa-times"></span></a>
                        </li>                    
                        <li>
                          <span class="aa-cartbox-total-title">
                            Total
                          </span>
                          <span class="aa-cartbox-total-price">
                            $500
                          </span>
                        </li>
                      </ul>
                      <a class="aa-cartbox-checkout aa-primary-btn" href="checkout.html">Checkout</a>
                    </div>
                  </div>
                  <!-- / cart box -->
                  <!-- search box -->
                  <div class="aa-search-box">
                    <form action="">
                      <input type="text" name="" id="" placeholder="Search here ex. 'man' ">
                      <button type="submit"><span class="fa fa-search"></span></button>
                    </form>
                  </div>
                  <!-- / search box -->             
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- / header bottom  -->
      </header>
      <section id="menu">
        <div class="container">
          <div class="menu-area">
            <!-- Navbar -->
            <div class="navbar navbar-default" role="navigation">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>          
              </div>
              <div class="navbar-collapse collapse">
                <!-- Left nav -->
                <ul class="nav navbar-nav">
                  <li><a href="{%url 'home_page' %}">Home</a></li>
                  {% for navbar in navbar_queryset %}
                  <li><a href="{{ navbar.url }}">{{navbar.title}} {% if navbar.category%}<span class="caret"></span>{%endif%}</a>
                    {% if navbar.category%}
                    <ul class="dropdown-menu">  
                      {% for category in navbar.categorymodel_set.all|slice:":8"%}              
                      <li><a href="/?category={{category.style}}">{{category.style}}</a></li>
                      {% endfor %}
                      {% if navbar.categorymodel_set.all|length > 8 %}
                      <li><a href="">And more.. <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          {% for category in navbar.categorymodel_set.all|slice:"8:"%}
                          <li><a href="/?category={{category.style}}">{{category.style}}</a></li> 
                          {% endfor %}                                     
                        </ul>
                      </li>
                      {% endif %}
                    </ul>
                    {% endif %}
                  </li>
                  
                  {% endfor %}
                  </li>
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </div>       
        </div>
      </section>
      <!-- / menu -->
      
      
     
    <body>
        {%block content%}
      {%endblock%}

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'asserts/js/bootstrap.js' %}"></script>  
  <!-- SmartMenus jQuery plugin -->
  <script type="text/javascript" src="{% static 'asserts/js/jquery.smartmenus.js' %}"></script>
  <!-- SmartMenus jQuery Bootstrap Addon -->
  <script type="text/javascript" src="{% static 'asserts/js/jquery.smartmenus.bootstrap.js' %}"></script>  
  <!-- To Slider JS -->
  <script src="{% static 'asserts/js/sequence.js' %}"></script>
  <script src="{% static 'asserts/js/sequence-theme.modern-slide-in.js' %}"></script>  
  <!-- Product view slider -->
  <script type="text/javascript" src="{% static 'asserts/js/jquery.simpleGallery.js' %}"></script>
  <script type="text/javascript" src="{% static 'asserts/js/jquery.simpleLens.js' %}"></script>
  <!-- slick slider -->
  <script type="text/javascript" src="{% static 'asserts/js/slick.js'%}"></script>
  <!-- Price picker slider -->
  <script type="text/javascript" src="{% static 'asserts/js/nouislider.js' %}"></script>
  <!-- Custom js -->
  <script src="{% static 'asserts/js/custom.js' %}"></script>

  <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
    <script>
        $(document).ready(function (){
            $('.category_filter').mouseover(function (){
          let categoryId = $(this).data('id')

             $.ajax({
            url: categoryId,
            method: "GET",

            success: function (data) {
                if (data){
                    $(".categories").html(data)
                }
                else{
                    $(".categories").html("Yoxdur")
                }



            },

            error: function (xhr, err, msg) {
                console.log(xhr, err, msg);
            }
        });
    })
        })
    </script>


{%block js%}
{% endblock %}
  

settings/templates/category_filter.html
{%load static%}

{%for i in categories %}
    <li><a href="/?category={{i.style}}">{{ i.style  }} </a></li>
{%endfor%}

settings/templates/contact.html
{%extends 'base.html' %}
{%load static%}
{%block content%}
  
  <!-- / catg header banner section -->
<!-- start contact section -->
 <section id="aa-contact">
   <div class="container">
     <div class="row">
       <div class="col-md-12">
         <div class="aa-contact-area">
           <div class="aa-contact-top">
             <h2>We are wating to assist you..</h2>
             <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, quos.</p>
           </div>
           <!-- contact map -->
           <div class="aa-contact-map">
              <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12153.321480433513!2d49.8109486!3d40.4015315!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd63ef03f7b58ae42!2sBravo%20Hypermarket!5e0!3m2!1sen!2s!4v1636028335573!5m2!1sen!2s" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
           </div>
           <!-- Contact address -->
           <div class="aa-contact-address">
            <form id="contact" action="" method="post">
              {%csrf_token%}
             <div class="row">
               <div class="col-md-8">
                 <div class="aa-contact-address-left">
                   <form class="comments-form contact-form" action="">
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">                        
                          <input name="name"  type="text" placeholder="Your Name" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">                        
                          <input name="email"  type="email" placeholder="Email" class="form-control">
                        </div>
                      </div>
                    </div>
                     <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">                        
                          <input name="subject"  type="text" placeholder="Subject" class="form-control">
                        </div>
                      </div>
                    </form>
                    </div>                  
                     
                    <div class="form-group">                        
                      <textarea  name="message" class="form-control" rows="3" placeholder="Message"></textarea>
                    </div>
                    <button class="aa-secondary-btn">Send</button>
                  </form>
                 </div>
               </div>
               <div class="col-md-4">
                 <div class="aa-contact-address-right">
                    {%for contact in contact_us_view %}
                    <h3>{{contact.name}}</h3>
                    <address>
                      <p>{{contact.adress}}</p>
                      <p><span class="fa fa-phone"></span>{{contact.number}}</p>
                      <p><span class="fa fa-envelope"></span>{{contact.email}}</p>
                    </address>
                    {%endfor%}
                 </div>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>

  <!-- Subscribe section -->
  <section id="aa-subscribe">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-subscribe-area">
            <h3>Subscribe our newsletter </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex, velit!</p>
            <form action="" class="aa-subscribe-form">
              <input type="email" name="" id="" placeholder="Enter your Email">
              <input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- / Subscribe section -->

  <!-- footer -->  
  <footer id="aa-footer">
    <!-- footer bottom -->
    <div class="aa-footer-top">
     <div class="container">
        <div class="row">
        <div class="col-md-12">
          <div class="aa-footer-top-area">
            <div class="row">
              <div class="col-md-3 col-sm-6">
                <div class="aa-footer-widget">
                  <h3>Main Menu</h3>
                  <ul class="aa-footer-nav">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Our Services</a></li>
                    <li><a href="#">Our Products</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Contact Us</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-3 col-sm-6">
                <div class="aa-footer-widget">
                  <div class="aa-footer-widget">
                    <h3>Knowledge Base</h3>
                    <ul class="aa-footer-nav">
                      <li><a href="#">Delivery</a></li>
                      <li><a href="#">Returns</a></li>
                      <li><a href="#">Services</a></li>
                      <li><a href="#">Discount</a></li>
                      <li><a href="#">Special Offer</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-md-3 col-sm-6">
                <div class="aa-footer-widget">
                  <div class="aa-footer-widget">
                    <h3>Useful Links</h3>
                    <ul class="aa-footer-nav">
                      <li><a href="#">Site Map</a></li>
                      <li><a href="#">Search</a></li>
                      <li><a href="#">Advanced Search</a></li>
                      <li><a href="#">Suppliers</a></li>
                      <li><a href="#">FAQ</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-md-3 col-sm-6">
                <div class="aa-footer-widget">
                  <div class="aa-footer-widget">
                    {%for contact in contact_us_view %}
                    <h3>{{contact.name}}</h3>
                    <address>
                      <p>{{contact.adress}}</p>
                      <p><span class="fa fa-phone"></span>{{contact.number}}</p>
                      <p><span class="fa fa-envelope"></span>{{contact.email}}</p>
                    </address>
                    <div class="aa-footer-social">
                      <a href=""><span class="{{contact.widgets}}"></span></a>
                      
                    </div>
                    {%endfor%}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
     </div>
    </div>
    <!-- footer-bottom -->
    <div class="aa-footer-bottom">
      <div class="container">
        <div class="row">
        <div class="col-md-12">
          <div class="aa-footer-bottom-area">
            <p>Designed by <a href="http://www.markups.io/">MarkUps.io</a></p>
            <div class="aa-footer-payment">
              <span class="fa fa-cc-mastercard"></span>
              <span class="fa fa-cc-visa"></span>
              <span class="fa fa-paypal"></span>
              <span class="fa fa-cc-discover"></span>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </footer>
  <!-- / footer -->
  <!-- Login Modal -->  
  <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">                      
        <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4>Login or Register</h4>
          <form class="aa-login-form" action="">
            <label for="">Username or Email address<span>*</span></label>
            <input type="text" placeholder="Username or email">
            <label for="">Password<span>*</span></label>
            <input type="password" placeholder="Password">
            <button class="aa-browse-btn" type="submit">Login</button>
            <label for="rememberme" class="rememberme"><input type="checkbox" id="rememberme"> Remember me </label>
            <p class="aa-lost-password"><a href="#">Lost your password?</a></p>
            <div class="aa-register-now">
              Don't have an account?<a href="account.html">Register now!</a>
            </div>
          </form>
        </div>                        
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div>


  </body>
</html>
{%endblock%}